# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 640)
        MainWindow.setMinimumSize(QtCore.QSize(960, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_menu = QtWidgets.QFrame(self.centralwidget)
        self.sidebar_menu.setMaximumSize(QtCore.QSize(60, 16777215))
        self.sidebar_menu.setStyleSheet("background-color: rgb(171, 213, 222);")
        self.sidebar_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar_menu.setObjectName("sidebar_menu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar_menu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.sidebar_menu)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sidebarButton = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebarButton.sizePolicy().hasHeightForWidth())
        self.sidebarButton.setSizePolicy(sizePolicy)
        self.sidebarButton.setStyleSheet("QPushButton {\n"
"                background-image: url(:/16x16/icons/16x16/cil-menu.png);\n"
"                background-position: left center;\n"
"                background-repeat: no-repeat;\n"
"                border: none;\n"
"                color: rgb(33, 53, 57);\n"
"                border-left: 22px solid rgb(120, 193, 207);\n"
"                background-color: rgb(120, 193, 207);\n"
"                text-align: left;\n"
"                padding-left: 45px;\n"
"                border-radius: 12px;\n"
"            }\n"
"            QPushButton[Active=true] {\n"
"                background-image: url(:/16x16/icons/16x16/cil-menu.png);\n"
"                background-position: left center;\n"
"                background-repeat: no-repeat;\n"
"                border: none;\n"
"                border-left: 22px solid  rgb(120, 193, 207);\n"
"                border-right: 45px solid rgb(120, 193, 207);\n"
"                background-color: rgb(120, 193, 207);\n"
"                text-align: left;\n"
"                padding-left: 45px;\n"
"                border-radius: 12px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(109, 176, 188);\n"
"                border-left: 22px solid rgb(109, 176, 188);\n"
"                border-radius: 12px;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(129, 209, 223);\n"
"                border-left: 22px solid rgb(129, 209, 223);\n"
"                border-radius: 12px;\n"
"            }")
        self.sidebarButton.setIconSize(QtCore.QSize(16, 16))
        self.sidebarButton.setObjectName("sidebarButton")
        self.verticalLayout_2.addWidget(self.sidebarButton)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.sidebar_menu)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.sidebar_menu)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.settingsButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setStyleSheet("QPushButton {\n"
"                background-image: url(:/16x16/icons/16x16/cil-menu.png);\n"
"                background-position: left center;\n"
"                background-repeat: no-repeat;\n"
"                border: none;\n"
"                color: rgb(33, 53, 57);\n"
"                border-left: 22px solid rgb(120, 193, 207);\n"
"                background-color: rgb(120, 193, 207);\n"
"                text-align: left;\n"
"                padding-left: 45px;\n"
"                border-radius: 12px;\n"
"            }\n"
"            QPushButton[Active=true] {\n"
"                background-image: url(:/16x16/icons/16x16/cil-menu.png);\n"
"                background-position: left center;\n"
"                background-repeat: no-repeat;\n"
"                border: none;\n"
"                border-left: 22px solid  rgb(120, 193, 207);\n"
"                border-right: 45px solid rgb(120, 193, 207);\n"
"                background-color: rgb(120, 193, 207);\n"
"                text-align: left;\n"
"                padding-left: 45px;\n"
"                border-radius: 12px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(109, 176, 188);\n"
"                border-left: 22px solid rgb(109, 176, 188);\n"
"                border-radius: 12px;\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(129, 209, 223);\n"
"                border-left: 22px solid rgb(129, 209, 223);\n"
"                border-radius: 12px;\n"
"            }")
        self.settingsButton.setIconSize(QtCore.QSize(16, 16))
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout_8.addWidget(self.settingsButton)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.sidebar_menu)
        self.mainbody = QtWidgets.QFrame(self.centralwidget)
        self.mainbody.setStyleSheet("background-color: rgb(240, 255, 255);")
        self.mainbody.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainbody.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainbody.setObjectName("mainbody")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mainbody)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainbody)
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_page = QtWidgets.QWidget()
        self.main_page.setObjectName("main_page")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_page)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.main_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(330, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(199, 227, 232);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.dails_view = QtWidgets.QListView(self.frame_4)
        self.dails_view.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(199, 227, 232);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(120, 193, 207);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(133, 216, 230);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(112, 184, 195);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.dails_view.setObjectName("dails_view")
        self.verticalLayout_14.addWidget(self.dails_view)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.main_page)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(500, 200))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/logo/icons/Genshin_Manager_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_13.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 398, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.main_page)
        self.page = QtWidgets.QWidget()
        self.page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.page.setObjectName("page")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.notes_frame = QtWidgets.QFrame(self.page)
        self.notes_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.notes_frame.setStyleSheet("background-color: rgb(199, 227, 232);")
        self.notes_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notes_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notes_frame.setObjectName("notes_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.notes_frame)
        self.verticalLayout_5.setContentsMargins(12, 0, 12, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.notes_frame)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.upd_realtime_button = QtWidgets.QPushButton(self.frame_6)
        self.upd_realtime_button.setMaximumSize(QtCore.QSize(70, 70))
        self.upd_realtime_button.setStyleSheet("QPushButton {\n"
"               border-radius: 34;\n"
"            }\n"
"QPushButton:hover {\n"
"                background-color: rgb(171, 213, 222);\n"
"                border-radius: 34;\n"
"            }\n"
"QPushButton:pressed {\n"
"                background-color: rgb(129, 209, 223);\n"
"                border-radius: 34;\n"
"            }")
        self.upd_realtime_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/16x16/icons/exp upd btn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upd_realtime_button.setIcon(icon)
        self.upd_realtime_button.setIconSize(QtCore.QSize(40, 40))
        self.upd_realtime_button.setDefault(False)
        self.upd_realtime_button.setFlat(True)
        self.upd_realtime_button.setObjectName("upd_realtime_button")
        self.horizontalLayout_5.addWidget(self.upd_realtime_button)
        self.verticalLayout_5.addWidget(self.frame_6)
        self.line_4 = QtWidgets.QFrame(self.notes_frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_5.addWidget(self.line_4)
        self.frame_7 = QtWidgets.QFrame(self.notes_frame)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.info_1 = QtWidgets.QLabel(self.frame_7)
        self.info_1.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.info_1.setFont(font)
        self.info_1.setText("")
        self.info_1.setObjectName("info_1")
        self.horizontalLayout_8.addWidget(self.info_1)
        self.verticalLayout_5.addWidget(self.frame_7)
        self.line_3 = QtWidgets.QFrame(self.notes_frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.frame_8 = QtWidgets.QFrame(self.notes_frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.info_2 = QtWidgets.QLabel(self.frame_8)
        self.info_2.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.info_2.setFont(font)
        self.info_2.setText("")
        self.info_2.setObjectName("info_2")
        self.horizontalLayout_9.addWidget(self.info_2)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.line_2 = QtWidgets.QFrame(self.notes_frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.frame_9 = QtWidgets.QFrame(self.notes_frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.info_3 = QtWidgets.QLabel(self.frame_9)
        self.info_3.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.info_3.setFont(font)
        self.info_3.setText("")
        self.info_3.setObjectName("info_3")
        self.horizontalLayout_10.addWidget(self.info_3)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.line = QtWidgets.QFrame(self.notes_frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_5.addWidget(self.line)
        self.frame_10 = QtWidgets.QFrame(self.notes_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.info_4 = QtWidgets.QLabel(self.frame_10)
        self.info_4.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.info_4.setFont(font)
        self.info_4.setText("")
        self.info_4.setObjectName("info_4")
        self.horizontalLayout_6.addWidget(self.info_4)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.line_5 = QtWidgets.QFrame(self.notes_frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_5.addWidget(self.line_5)
        self.frame_11 = QtWidgets.QFrame(self.notes_frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.info_5 = QtWidgets.QLabel(self.frame_11)
        self.info_5.setMaximumSize(QtCore.QSize(90, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.info_5.setFont(font)
        self.info_5.setText("")
        self.info_5.setObjectName("info_5")
        self.horizontalLayout_7.addWidget(self.info_5)
        self.verticalLayout_5.addWidget(self.frame_11)
        self.horizontalLayout_4.addWidget(self.notes_frame)
        self.frame_12 = QtWidgets.QFrame(self.page)
        self.frame_12.setMaximumSize(QtCore.QSize(550, 16777215))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_9.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtWidgets.QLabel(self.frame_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.info_6 = QtWidgets.QLabel(self.frame_13)
        self.info_6.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.info_6.setFont(font)
        self.info_6.setText("")
        self.info_6.setObjectName("info_6")
        self.horizontalLayout_11.addWidget(self.info_6)
        self.verticalLayout_9.addWidget(self.frame_13)
        self.characters_view = QtWidgets.QListView(self.frame_12)
        self.characters_view.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.characters_view.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(199, 227, 232);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(120, 193, 207);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(133, 216, 230);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(112, 184, 195);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.characters_view.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.characters_view.setObjectName("characters_view")
        self.verticalLayout_9.addWidget(self.characters_view)
        self.horizontalLayout_4.addWidget(self.frame_12)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_17 = QtWidgets.QFrame(self.page_2)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_11.addWidget(self.label_13)
        self.line_9 = QtWidgets.QFrame(self.frame_17)
        self.line_9.setMaximumSize(QtCore.QSize(130, 16777215))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.verticalLayout_11.addWidget(self.line_9)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.frame_18)
        self.label_10.setMaximumSize(QtCore.QSize(83, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.line_6 = QtWidgets.QFrame(self.frame_18)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_13.addWidget(self.line_6)
        self.label_11 = QtWidgets.QLabel(self.frame_18)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(282, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_13.addWidget(self.label_11)
        self.line_7 = QtWidgets.QFrame(self.frame_18)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_13.addWidget(self.line_7)
        self.label_12 = QtWidgets.QLabel(self.frame_18)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_13.addWidget(self.label_12)
        self.verticalLayout_11.addWidget(self.frame_18)
        self.primos_view = QtWidgets.QListView(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.primos_view.setFont(font)
        self.primos_view.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(199, 227, 232);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(120, 193, 207);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(133, 216, 230);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(112, 184, 195);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.primos_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.primos_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.primos_view.setObjectName("primos_view")
        self.verticalLayout_11.addWidget(self.primos_view)
        self.horizontalLayout_12.addWidget(self.frame_17)
        self.frame_14 = QtWidgets.QFrame(self.page_2)
        self.frame_14.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.prim_graphic_1 = PlotWidget(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prim_graphic_1.sizePolicy().hasHeightForWidth())
        self.prim_graphic_1.setSizePolicy(sizePolicy)
        self.prim_graphic_1.setMinimumSize(QtCore.QSize(0, 0))
        self.prim_graphic_1.setStyleSheet("background-color: rgb(199, 227, 232);")
        self.prim_graphic_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prim_graphic_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prim_graphic_1.setObjectName("prim_graphic_1")
        self.verticalLayout_6.addWidget(self.prim_graphic_1)
        self.prim_graphic_2 = PlotWidget(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prim_graphic_2.sizePolicy().hasHeightForWidth())
        self.prim_graphic_2.setSizePolicy(sizePolicy)
        self.prim_graphic_2.setStyleSheet("background-color: rgb(199, 227, 232);")
        self.prim_graphic_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prim_graphic_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prim_graphic_2.setObjectName("prim_graphic_2")
        self.verticalLayout_6.addWidget(self.prim_graphic_2)
        self.horizontalLayout_12.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.page_2)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.page_5)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_19 = QtWidgets.QFrame(self.page_5)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_7.addWidget(self.label_14)
        self.line_8 = QtWidgets.QFrame(self.frame_19)
        self.line_8.setMaximumSize(QtCore.QSize(130, 16777215))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.verticalLayout_7.addWidget(self.line_8)
        self.frame_23 = QtWidgets.QFrame(self.frame_19)
        self.frame_23.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_17.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.frame_23)
        self.label_19.setMaximumSize(QtCore.QSize(83, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.line_12 = QtWidgets.QFrame(self.frame_23)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_17.addWidget(self.line_12)
        self.label_20 = QtWidgets.QLabel(self.frame_23)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(282, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_17.addWidget(self.label_20)
        self.line_13 = QtWidgets.QFrame(self.frame_23)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_17.addWidget(self.line_13)
        self.label_21 = QtWidgets.QLabel(self.frame_23)
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_17.addWidget(self.label_21)
        self.verticalLayout_7.addWidget(self.frame_23)
        self.resins_view = QtWidgets.QListView(self.frame_19)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.resins_view.setFont(font)
        self.resins_view.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(199, 227, 232);\n"
"    width: 14px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
"QScrollBar::handle:vertical {    \n"
"    background-color: rgb(120, 193, 207);\n"
"    min-height: 30px;\n"
"    border-radius: 7px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color:  rgb(133, 216, 230);\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: rgb(112, 184, 195);\n"
"}\n"
"\n"
"/* BTN TOP - SCROLLBAR */\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background-color:  rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* BTN BOTTOM - SCROLLBAR */\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background-color: rgb(183, 208, 213);\n"
"    height: 15px;\n"
"    border-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover {    \n"
"    background-color: rgb(164, 213, 209);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {    \n"
"    background-color: rgb(101, 183, 184);\n"
"}\n"
"\n"
"/* RESET ARROW */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.resins_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.resins_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.resins_view.setObjectName("resins_view")
        self.verticalLayout_7.addWidget(self.resins_view)
        self.horizontalLayout_14.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(self.page_5)
        self.frame_20.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_21 = PlotWidget(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_21.sizePolicy().hasHeightForWidth())
        self.frame_21.setSizePolicy(sizePolicy)
        self.frame_21.setStyleSheet("background-color: rgb(199, 227, 232);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_12.addWidget(self.frame_21)
        self.frame_22 = PlotWidget(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_22.sizePolicy().hasHeightForWidth())
        self.frame_22.setSizePolicy(sizePolicy)
        self.frame_22.setStyleSheet("background-color: rgb(199, 227, 232);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_12.addWidget(self.frame_22)
        self.horizontalLayout_14.addWidget(self.frame_20)
        self.stackedWidget.addWidget(self.page_5)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.settings_page)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.settingsWarning = QtWidgets.QLabel(self.settings_page)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(12)
        self.settingsWarning.setFont(font)
        self.settingsWarning.setStyleSheet("color: rgb(222, 83, 86);")
        self.settingsWarning.setAlignment(QtCore.Qt.AlignCenter)
        self.settingsWarning.setObjectName("settingsWarning")
        self.verticalLayout_10.addWidget(self.settingsWarning)
        self.ltoken = QtWidgets.QLineEdit(self.settings_page)
        self.ltoken.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 6px;")
        self.ltoken.setText("")
        self.ltoken.setAlignment(QtCore.Qt.AlignCenter)
        self.ltoken.setClearButtonEnabled(False)
        self.ltoken.setObjectName("ltoken")
        self.verticalLayout_10.addWidget(self.ltoken)
        self.ltuid = QtWidgets.QLineEdit(self.settings_page)
        self.ltuid.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 6px;")
        self.ltuid.setText("")
        self.ltuid.setAlignment(QtCore.Qt.AlignCenter)
        self.ltuid.setObjectName("ltuid")
        self.verticalLayout_10.addWidget(self.ltuid)
        self.saveButton = QtWidgets.QPushButton(self.settings_page)
        self.saveButton.setStyleSheet("QPushButton {\n"
"background: #FFFFFF;\n"
"border-radius: 6px;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(37, 128, 188);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(45, 174, 221);\n"
"}")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_10.addWidget(self.saveButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.settings_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.mainbody)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sidebarButton.setText(_translate("MainWindow", "MENU"))
        self.settingsButton.setText(_translate("MainWindow", "SETTINGS"))
        self.label_5.setText(_translate("MainWindow", "Дневник"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Выполненно<br/>поручений:</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>Награда за</p><p>поручения:</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Еженедельные<br/>боссы:</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Смола:"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>До полного<br/>восстановления:</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "Экспедиции"))
        self.label_13.setText(_translate("MainWindow", "Примагемы:"))
        self.label_10.setText(_translate("MainWindow", "Кол-во:"))
        self.label_11.setText(_translate("MainWindow", "За что:"))
        self.label_12.setText(_translate("MainWindow", "Дата:"))
        self.label_14.setText(_translate("MainWindow", "Смола:"))
        self.label_19.setText(_translate("MainWindow", "Кол-во:"))
        self.label_20.setText(_translate("MainWindow", "За что:"))
        self.label_21.setText(_translate("MainWindow", "Дата:"))
        self.label.setText(_translate("MainWindow", "Settings:"))
        self.settingsWarning.setText(_translate("MainWindow", "Проверьте введенные данные"))
        self.ltoken.setPlaceholderText(_translate("MainWindow", "ltoken"))
        self.ltuid.setPlaceholderText(_translate("MainWindow", "ltuid"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
from pyqtgraph import PlotWidget
import resourses_rc
