# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cookie_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(316, 404)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cookie_icon/mini_cookie.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background: #C4C4C4;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ltokenEdit = QtWidgets.QLineEdit(self.frame)
        self.ltokenEdit.setEnabled(True)
        self.ltokenEdit.setGeometry(QtCore.QRect(53, 70, 210, 56))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ltokenEdit.setFont(font)
        self.ltokenEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ltokenEdit.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 6px;")
        self.ltokenEdit.setText("")
        self.ltokenEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.ltokenEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ltokenEdit.setReadOnly(False)
        self.ltokenEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.ltokenEdit.setObjectName("ltokenEdit")
        self.ltuidEdit = QtWidgets.QLineEdit(self.frame)
        self.ltuidEdit.setGeometry(QtCore.QRect(53, 149, 210, 53))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ltuidEdit.sizePolicy().hasHeightForWidth())
        self.ltuidEdit.setSizePolicy(sizePolicy)
        self.ltuidEdit.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ltuidEdit.setFont(font)
        self.ltuidEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.ltuidEdit.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 6px;")
        self.ltuidEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.ltuidEdit.setClearButtonEnabled(False)
        self.ltuidEdit.setObjectName("ltuidEdit")
        self.okButton = QtWidgets.QPushButton(self.frame)
        self.okButton.setGeometry(QtCore.QRect(101, 286, 114, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.okButton.setFont(font)
        self.okButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.okButton.setStyleSheet("QPushButton {\n"
"border: 0;\n"
"background: #FFFDFD;\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(37, 128, 188);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(45, 174, 221);\n"
"}")
        self.okButton.setObjectName("okButton")
        self.faqButton = QtWidgets.QPushButton(self.frame)
        self.faqButton.setGeometry(QtCore.QRect(185, 211, 103, 18))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.faqButton.setFont(font)
        self.faqButton.setStyleSheet("border: 0px;\n"
"color: #FFFFFF;")
        self.faqButton.setObjectName("faqButton")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cookie"))
        self.ltokenEdit.setPlaceholderText(_translate("Dialog", "Your ltoken"))
        self.ltuidEdit.setPlaceholderText(_translate("Dialog", "Your ltuid"))
        self.okButton.setText(_translate("Dialog", "Ок"))
        self.faqButton.setText(_translate("Dialog", "Проблемы?"))
import resourse.icons_rc
