# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uid_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(316, 201)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background: rgb(210, 232, 232);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.uidEdit = QtWidgets.QLineEdit(self.frame)
        self.uidEdit.setGeometry(QtCore.QRect(53, 30, 210, 56))
        self.uidEdit.setStyleSheet("background: #FFFFFF;\n"
"border-radius: 6px;")
        self.uidEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.uidEdit.setObjectName("uidEdit")
        self.uidButton = QtWidgets.QPushButton(self.frame)
        self.uidButton.setGeometry(QtCore.QRect(100, 120, 114, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.uidButton.setFont(font)
        self.uidButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.uidButton.setStyleSheet("QPushButton {\n"
"border: 0;\n"
"background: #FFFDFD;\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(37, 128, 188);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(45, 174, 221);\n"
"}")
        self.uidButton.setObjectName("uidButton")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.uidEdit.setPlaceholderText(_translate("Dialog", "Your uid"))
        self.uidButton.setText(_translate("Dialog", "Ок"))
